- be/src/main/java/com/ssb/scalendar/domain/user/controller/AuthController.java
- be/src/main/java/com/ssb/scalendar/domain/user/controller/TestController.java
- be/src/main/java/com/ssb/scalendar/domain/user/dto/request/LoginRequestDto.java
- be/src/main/java/com/ssb/scalendar/domain/user/dto/response/LoginResponseDto.java
- be/src/main/java/com/ssb/scalendar/domain/user/repository/UserRepository.java
- be/src/main/java/com/ssb/scalendar/domain/user/service/AuthService.java
- be/src/main/java/com/ssb/scalendar/global/config/SecurityConfig.java
- be/src/main/java/com/ssb/scalendar/global/exception/GlobalExceptionHandler.java
- be/src/main/java/com/ssb/scalendar/global/security/CustomUserDetailsService.java
- be/src/main/java/com/ssb/scalendar/global/security/handler/CustomAccessDeniedHandler.java
- be/src/main/java/com/ssb/scalendar/global/security/handler/JwtAuthenticationEntryPoint.java
- be/src/main/java/com/ssb/scalendar/global/security/handler/tmpfiles
- be/src/main/java/com/ssb/scalendar/global/security/jwt/JwtAuthenticationFilter.java
- be/src/main/java/com/ssb/scalendar/global/security/jwt/JwtTokenProvider.java
- be/src/main/java/com/ssb/scalendar/global/security/jwt/tmpfiles
- be/src/main/resources/application.properties
- BCW-14 [BE] 로그인 API 구현
- login api 구현
- cors 추가
> BCW-14 [BE] 로그인 API 구현

- fe/src/App.css
- fe/src/RootLayout.jsx
- fe/src/components/DayHeader.jsx
- fe/src/components/day/Diary.jsx
- fe/src/components/day/Schedule.jsx
- fe/src/components/day/Task.jsx
- fe/src/index.css
- fe/src/pages/Day.jsx
- fe/src/router/index.jsx
- BCW-17 [FE] 세부 페이지 프레임 생성
- day 세부 페이지 프레임 생성 및 기본 css 적용
- url이 yyyy-mm-dd 형식으로 전달되지 않을 경우 calendar 페이지로 리다이렉트되도록 설정
- RootLayout.jsx에 Outlet 적용되지 않은 오류 수정
- 페이지 가로 길이 줄였을 때 좌우 여백이 없어서 전체 css에 좌우 padding 추가
> BCW-17 [FE] 세부 페이지 프레임 생성

- fe/src/App.jsx
- fe/src/AuthProvider.jsx
- fe/src/RootLayout.jsx
- fe/src/pages/Login.jsx
- BCW-31 [FE] 로그인 페이지 생성 수정
- 인증 로직 분리 : AuthProvider 생성 -> RootLayout, App 구조 개선
- 로그인 시 에러 메세지 수정 및 색상 변경
> BCW-31 [FE] 로그인 페이지 생성 수정

- fe/src/api/authApi.js
- fe/src/pages/Signup.jsx
- BCW-33 [FE] 회원가입 - 이메일 중복체크, 비밀번호 확인 기능
- 이메일 중복체크 기능 구현
- 비밀번호 확인 기능 구현
- 각종 유효성 확인 기능 구현
- s-calendar 이동 기능 구현 + 크기 조정
> BCW-33 [FE] 회원가입 - 이메일 중복체크, 비밀번호 확인 기능

- .github/workflows/deploy.yml
- BCW-37 [DP] 1차 배포 수정 - 1
- 누락된 환경 변수 추가
> BCW-37 [DP] 1차 배포 수정 - 1

- .github/workflows/deploy.yml
- docker-compose.yml
- BCW-38 [DP] 1차 배포 수정 - 2
- 캐시 추가
> BCW-38 [DP] 1차 배포 수정 - 2

- docker-compose.yml
- fe/nginx.conf
- BCW-39 HTTPS 적용
- https 설정 추가
> BCW-39 HTTPS 적용

- docker-compose.yml
- fe/.env.example
- BCW-43 [DP] Nginx에 환경변수 적용3
- docker-compose 파일 수정
> BCW-43 [DP] Nginx에 환경변수 적용3

- be/src/main/java/com/ssb/scalendar/global/config/SecurityConfig.java
- BCW-46 [DP] CORS origin 수정 1
- cors origin 수정
> BCW-46 [DP] CORS origin 수정 1

- fe/src/pages/Signup.jsx
- BCW-51 [FE] 회원가입 유효성 문구 수정 및 이동 수정
-  유효성 검사 문구 수정 및 회원가입 후 이동 수정
> BCW-51 [FE] 회원가입 유효성 문구 수정 및 이동 수정

- fe/src/components/Header.jsx
- BCW-50 [FE] 헤더 리팩토링 및 로그인 유무에 따른 기능 추가
- 로그인에 따른 로그인/로그아웃 교체 기능 및 로그아웃 시 랜딩페이지로 이동 구현
- header size, text-xl로 변경
> BCW-50 [FE] 헤더 리팩토링 및 로그인 유무에 따른 기능 추가

- fe/src/components/Header.jsx
- BCW-53 [FE] Header component의 빠진 이동 로직 추가
- scalendar 누를 시 landing page로 이동 구현
> BCW-53 [FE] Header component의 빠진 이동 로직 추가

- fe/src/components/Header.jsx
- fe/src/pages/Signup.jsx
- BCW-54 [FE] Header component의 빠진 이동 로직 추가 2
- header의 s-calendar의 이동을 로그인 상태에 따라 구현
- 회원가입 화면에 autoComplete 추가 및 입력란 width 수정
> BCW-54 [FE] Header component의 빠진 이동 로직 추가 2

- fe/src/api/TaskApi.js
- fe/src/api/scheduleApi.js
- fe/src/components/Empty.jsx
- fe/src/components/Header.jsx
- fe/src/components/day/DiaryCreate.jsx
- fe/src/components/day/Schedule.jsx
- fe/src/components/day/ScheduleCreate.jsx
- fe/src/components/day/Task.jsx
- fe/src/components/day/TaskCreate.jsx
- fe/src/index.css
- fe/src/pages/Login.jsx
- fe/src/router/index.jsx
- BCW-18 [FE] 일정 관련 및 할일 추가 페이지 생성
- 일정 생성 페이지 추가
- 일정 조회 페이지 추가
- 할일 생성 페이지 추가
- empty 컴포넌트 추가
> BCW-18 [FE] 일정 관련 및 할일 추가 페이지 생성

- be/src/main/java/com/ssb/scalendar/domain/common/projection/DailyCount.java
- be/src/main/java/com/ssb/scalendar/domain/schedule/controller/ScheduleController.java
- be/src/main/java/com/ssb/scalendar/domain/schedule/dto/response/MonthlyScheduleResponseDto.java
- be/src/main/java/com/ssb/scalendar/domain/schedule/repository/ScheduleRepository.java
- be/src/main/java/com/ssb/scalendar/domain/schedule/service/ScheduleService.java
- BCW-57 [BE] 일정 조회 by day API 보완
- 일정 조회 by day API 데이터 시간 순으로 정렬
- DailyCount 인터페이스 파일 위치 변경
> BCW-57 [BE] 일정 조회 by day API 보완

- fe/src/pages/Login.jsx
- fe/src/pages/Signup.jsx
- BCW-34 [FE] 로그인 페이지 - 레이아웃 배치 통일
- 회원가입 페이지와 양식 통일
- 색상, 텍스트 크기 조정
- 에러 문구 위치 조정
> BCW-34 [FE] 로그인 페이지 - 레이아웃 배치 통일

- be/src/main/java/com/ssb/scalendar/domain/task/controller/TaskController.java
- be/src/main/java/com/ssb/scalendar/domain/task/dto/request/CheckTaskRequestDto.java
- be/src/main/java/com/ssb/scalendar/domain/task/dto/request/TaskCreateRequestDto.java
- be/src/main/java/com/ssb/scalendar/domain/task/dto/response/CheckTaskResponseDto.java
- be/src/main/java/com/ssb/scalendar/domain/task/dto/response/MonthlyTaskResponseDto.java
- be/src/main/java/com/ssb/scalendar/domain/task/dto/response/TaskResponseDto.java
- be/src/main/java/com/ssb/scalendar/domain/task/entity/Task.java
- be/src/main/java/com/ssb/scalendar/domain/task/repository/TaskRepository.java
- be/src/main/java/com/ssb/scalendar/domain/task/service/TaskService.java
- BCW 25-[BE] 할일 API 구현
- 할 일 생성 api 구현
- 할 일 월간 조회 기능 api 구현
- 할 일 일간 조회 기능 api 구현
- 할 일 체크박스 상태 업데이트 api 구현
- 할 일 삭제 기능 api 구현
> BCW 25-[BE] 할일 API 구현

- fe/src/api/TaskApi.js
- fe/src/api/scheduleApi.js
- fe/src/components/day/Schedule.jsx
- fe/src/components/day/ScheduleCreate.jsx
- fe/src/components/day/Task.jsx
- fe/src/components/day/TaskCreate.jsx
- BCW-21 [FE] 할일 조회 페이지 생성
- 할일 페이지 api 연결
> BCW-21 [FE] 할일 조회 페이지 생성

- be/src/main/java/com/ssb/scalendar/domain/diary/entity/Diary.java
- be/src/main/java/com/ssb/scalendar/domain/diary/service/DiaryService.java
- be/src/main/java/com/ssb/scalendar/global/exception/GlobalExceptionHandler.java
- transactional 추가
- entity 컬럼 설정 추가
- BCW-63 [BE] 일기 api 보완
- transactional 추가
- entity 컬럼 설정 추가
> BCW-63 [BE] 일기 api 보완

- fe/package-lock.json
- fe/package.json
- fe/src/api/diaryApi.js
- fe/src/components/DayHeader.jsx
- fe/src/components/day/Diary.jsx
- fe/src/components/day/DiaryCreate.jsx
- fe/src/components/day/diary/DiaryEditor.jsx
- fe/src/components/day/diary/DiaryForm.jsx
- fe/src/components/day/diary/EditorToolbar.jsx
- fe/src/components/day/diary/styles/DiaryEditor.css
- fe/src/components/day/diary/styles/editorStyles.js
- fe/src/pages/Day.jsx
- fe/src/router/index.jsx
- BCW-22 [FE] 일기 조회, 수정 페이지 생성
- tiptap 관련 패키지 설치
- tiptap 리치 텍스트 에디터 사용해 일기 페이지 구현
- 일기 생성, 조회, 삭제 기능까지 구현됨
- day 페이지 리팩토링 
- 리액트 기능(useParams, NavLink) 사용하도록 수정
- router에 등록되지 않은 패스로 접근 시, 달력 페이지로 리다이렉트되도록 수정
> BCW-22 [FE] 일기 조회, 수정 페이지 생성

- be/src/main/java/com/ssb/scalendar/domain/diary/dto/request/DiaryUpdateRequestDto.java
- be/src/main/java/com/ssb/scalendar/domain/diary/entity/Diary.java
- fe/src/components/day/Diary.jsx
- fe/src/components/day/DiaryCreate.jsx
- fe/src/components/day/diary/styles/DiaryEditor.css
- BCW-23 [FE] 일기 수정 기능 구현
- 일기 수정 페이지 구현
- 일기 조회 페이지에서 형광펜 적용 안 되는 오류 해결
- 일기 수정 api에서 selectedDate가 null로 수정되는 오류 해결
> BCW-23 [FE] 일기 수정 기능 구현

- fe/src/App.css
- fe/src/components/Footer.jsx
- fe/src/pages/Home.jsx
- BCW-65 [FE] 랜딩 페이지 세부사항 추가 및 수정
- 타이틀의 S-Calendar에 동그라미 모양 추가
- 일정, 할일, 일기 텍스트 및 하이라이트 추가
- 위의 꾸미기 기능을 위해 App.css에 설정사항 추가
> BCW-65 [FE] 랜딩 페이지 세부사항 추가 및 수정

- fe/src/components/Footer.jsx
- fe/src/components/day/Schedule.jsx
- fe/src/components/day/ScheduleCreate.jsx
- fe/src/components/day/TaskCreate.jsx
- fe/src/index.css
- fe/src/pages/Day.jsx
- BCW-20 [FE] 일정 조회 페이지 및 할일 생성 페이지 디자인 설정
- 일정 조회 페이지 디자인 설정
- 할일 생성 페이지 디자인 설정
> BCW-20 [FE] 일정 조회 페이지 및 할일 생성 페이지 디자인 설정

- fe/src/components/day/Schedule.jsx
- fe/src/components/day/ScheduleCreate.jsx
- fe/src/components/day/Task.jsx
- fe/src/components/day/TaskCreate.jsx
- fe/src/index.css
- BCW-66 [FE] 할 일 조회 페이지 디자인 설정
- 할 일 조회 페이지 디자인 설정
- 스크롤바 디자인 설정
> BCW-66 [FE] 할 일 조회 페이지 디자인 설정

- fe/src/components/day/ScheduleCreate.jsx
- fe/src/components/day/Task.jsx
- fe/src/components/day/TaskCreate.jsx
- fe/src/index.css
- BCW-68 [FE] 일정, 조회 글자 수 제한 추가 및 디자인 설정
- 일정, 조회 글자 수 제한 설정
- 일정 조회 디자인 설정
> BCW-68 [FE] 일정, 조회 글자 수 제한 추가 및 디자인 설정

- fe/src/components/Footer.jsx
- fe/src/components/Header.jsx
- fe/src/pages/Home.jsx
- BCW-69 [FE] 랜딩 페이지 추가 세부사항 수정 및 이동 히스토리 제거
- 달력 또는 랜딩 페이지로 이동 후 히스토리 삭제하여 되돌아가기 기능 제거
- 랜딩페이지의 세부 데코 수정
> BCW-69 [FE] 랜딩 페이지 추가 세부사항 수정 및 이동 히스토리 제거

- fe/src/components/Empty.jsx
- fe/src/components/day/Diary.jsx
- fe/src/components/day/Schedule.jsx
- fe/src/components/day/Task.jsx
- fe/src/pages/Day.jsx
- BCW-73 [FE] day 페이지 디자인 설정 및 비로그인 접근 제한
- day 페이지 디자인 설정
- 비로그인 접근 제한
> BCW-73 [FE] day 페이지 디자인 설정 및 비로그인 접근 제한

- be/src/main/java/com/ssb/scalendar/domain/task/dto/response/MonthlyTaskResponseDto.java
-BCW-77-[FE] 할 일 DTO 수정
- MonthlyTaskResponseDto의 변수 date -> day 로 수정
> BCW-77-[FE] 할 일 DTO 수정

- fe/src/components/day/DiaryCreate.jsx
- fe/src/components/day/ScheduleCreate.jsx
- BCW-[FE] 일기 수정 기능 오류 수정
- 디자인 수정하면서 변경한 코드에서 오류가 발생해 수정.
- 일정 페이지 관련 대리 수정을 요청 받아 수정.
> BCW-[FE] 일기 수정 기능 오류 수정(+ 일정 생성 페이지 수정)

- .github/workflows/deploy.yml
- docker username 추가
- BCW-82 [DP] 환경변수 설정 오류 해결
> BCW-82 [DP] 환경변수 설정 오류 해결
